# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_filenamemodel_photo_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='AccessAuthority'),
        ),
    ]
