# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_filenamemodel_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='score1',
            field=models.DecimalField(decimal_places=10, max_digits=11, null='true'),
        ),
        migrations.AlterField(
            model_name='result',
            name='score10',
            field=models.DecimalField(decimal_places=10, max_digits=11, null='true'),
        ),
        migrations.AlterField(
            model_name='result',
            name='score2',
            field=models.DecimalField(decimal_places=10, max_digits=11, null='true'),
        ),
        migrations.AlterField(
            model_name='result',
            name='score3',
            field=models.DecimalField(decimal_places=10, max_digits=11, null='true'),
        ),
        migrations.AlterField(
            model_name='result',
            name='score4',
            field=models.DecimalField(decimal_places=10, max_digits=11, null='true'),
        ),
        migrations.AlterField(
            model_name='result',
            name='score5',
            field=models.DecimalField(decimal_places=10, max_digits=11, null='true'),
        ),
        migrations.AlterField(
            model_name='result',
            name='score6',
            field=models.DecimalField(decimal_places=10, max_digits=11, null='true'),
        ),
        migrations.AlterField(
            model_name='result',
            name='score7',
            field=models.DecimalField(decimal_places=10, max_digits=11, null='true'),
        ),
        migrations.AlterField(
            model_name='result',
            name='score8',
            field=models.DecimalField(decimal_places=10, max_digits=11, null='true'),
        ),
        migrations.AlterField(
            model_name='result',
            name='score9',
            field=models.DecimalField(decimal_places=10, max_digits=11, null='true'),
        ),
    ]
