# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-13 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180813_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result1',
            field=models.CharField(max_length=50, null='true'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result10',
            field=models.CharField(max_length=50, null='true'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result2',
            field=models.CharField(max_length=50, null='true'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result3',
            field=models.CharField(max_length=50, null='true'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result4',
            field=models.CharField(max_length=50, null='true'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result5',
            field=models.CharField(max_length=50, null='true'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result6',
            field=models.CharField(max_length=50, null='true'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result7',
            field=models.CharField(max_length=50, null='true'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result8',
            field=models.CharField(max_length=50, null='true'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result9',
            field=models.CharField(max_length=50, null='true'),
        ),
    ]
